# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AWSS3Upload' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AWSS3'
  # Pods for AWSS3Upload

end
